--- #YAML:1.0
name:                Tie-File-AnyData-Bio-Fasta
version:             0.01
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Test::More:                    0
    Tie::File::AnyData:            0.01
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Miguel Pignatelli <motif@cpan.org>
